// Auto-generated code. Do not edit manually!
#![allow(unused)]
use crate::prelude::*;

pub const FONT_TILESET: TilesetData =
    TilesetData { tiles: &FONT_TILES, colors: None, sub_palettes: None };

pub const FONT_MAP: Tilemap<90> = Tilemap {
    columns: 10,
    rows: 9,
    cells: [
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(0) },
        Cell { id: TileID(2), flags: TileFlags(0) },
        Cell { id: TileID(3), flags: TileFlags(0) },
        Cell { id: TileID(4), flags: TileFlags(0) },
        Cell { id: TileID(5), flags: TileFlags(0) },
        Cell { id: TileID(6), flags: TileFlags(0) },
        Cell { id: TileID(7), flags: TileFlags(0) },
        Cell { id: TileID(8), flags: TileFlags(0) },
        Cell { id: TileID(9), flags: TileFlags(0) },
        Cell { id: TileID(10), flags: TileFlags(0) },
        Cell { id: TileID(11), flags: TileFlags(0) },
        Cell { id: TileID(12), flags: TileFlags(0) },
        Cell { id: TileID(13), flags: TileFlags(0) },
        Cell { id: TileID(14), flags: TileFlags(0) },
        Cell { id: TileID(15), flags: TileFlags(0) },
        Cell { id: TileID(16), flags: TileFlags(0) },
        Cell { id: TileID(17), flags: TileFlags(0) },
        Cell { id: TileID(18), flags: TileFlags(0) },
        Cell { id: TileID(19), flags: TileFlags(0) },
        Cell { id: TileID(20), flags: TileFlags(0) },
        Cell { id: TileID(21), flags: TileFlags(0) },
        Cell { id: TileID(22), flags: TileFlags(0) },
        Cell { id: TileID(23), flags: TileFlags(0) },
        Cell { id: TileID(24), flags: TileFlags(0) },
        Cell { id: TileID(25), flags: TileFlags(0) },
        Cell { id: TileID(26), flags: TileFlags(0) },
        Cell { id: TileID(27), flags: TileFlags(0) },
        Cell { id: TileID(28), flags: TileFlags(0) },
        Cell { id: TileID(29), flags: TileFlags(0) },
        Cell { id: TileID(30), flags: TileFlags(0) },
        Cell { id: TileID(31), flags: TileFlags(0) },
        Cell { id: TileID(32), flags: TileFlags(0) },
        Cell { id: TileID(33), flags: TileFlags(0) },
        Cell { id: TileID(34), flags: TileFlags(0) },
        Cell { id: TileID(35), flags: TileFlags(0) },
        Cell { id: TileID(36), flags: TileFlags(0) },
        Cell { id: TileID(37), flags: TileFlags(0) },
        Cell { id: TileID(38), flags: TileFlags(0) },
        Cell { id: TileID(39), flags: TileFlags(0) },
        Cell { id: TileID(40), flags: TileFlags(0) },
        Cell { id: TileID(41), flags: TileFlags(0) },
        Cell { id: TileID(42), flags: TileFlags(0) },
        Cell { id: TileID(43), flags: TileFlags(0) },
        Cell { id: TileID(44), flags: TileFlags(0) },
        Cell { id: TileID(45), flags: TileFlags(0) },
        Cell { id: TileID(46), flags: TileFlags(0) },
        Cell { id: TileID(47), flags: TileFlags(0) },
        Cell { id: TileID(48), flags: TileFlags(0) },
        Cell { id: TileID(49), flags: TileFlags(0) },
        Cell { id: TileID(50), flags: TileFlags(0) },
        Cell { id: TileID(51), flags: TileFlags(0) },
        Cell { id: TileID(52), flags: TileFlags(0) },
        Cell { id: TileID(53), flags: TileFlags(0) },
        Cell { id: TileID(54), flags: TileFlags(0) },
        Cell { id: TileID(55), flags: TileFlags(0) },
        Cell { id: TileID(56), flags: TileFlags(0) },
        Cell { id: TileID(57), flags: TileFlags(0) },
        Cell { id: TileID(58), flags: TileFlags(0) },
        Cell { id: TileID(59), flags: TileFlags(0) },
        Cell { id: TileID(60), flags: TileFlags(0) },
        Cell { id: TileID(61), flags: TileFlags(0) },
        Cell { id: TileID(62), flags: TileFlags(0) },
        Cell { id: TileID(63), flags: TileFlags(0) },
        Cell { id: TileID(64), flags: TileFlags(0) },
        Cell { id: TileID(65), flags: TileFlags(0) },
        Cell { id: TileID(64), flags: TileFlags(128) },
        Cell { id: TileID(66), flags: TileFlags(0) },
        Cell { id: TileID(67), flags: TileFlags(0) },
        Cell { id: TileID(68), flags: TileFlags(0) },
        Cell { id: TileID(69), flags: TileFlags(0) },
        Cell { id: TileID(70), flags: TileFlags(0) },
        Cell { id: TileID(71), flags: TileFlags(0) },
        Cell { id: TileID(72), flags: TileFlags(0) },
        Cell { id: TileID(73), flags: TileFlags(0) },
        Cell { id: TileID(74), flags: TileFlags(0) },
        Cell { id: TileID(75), flags: TileFlags(0) },
        Cell { id: TileID(75), flags: TileFlags(128) },
        Cell { id: TileID(76), flags: TileFlags(0) },
        Cell { id: TileID(77), flags: TileFlags(0) },
        Cell { id: TileID(78), flags: TileFlags(0) },
        Cell { id: TileID(79), flags: TileFlags(0) },
        Cell { id: TileID(80), flags: TileFlags(0) },
        Cell { id: TileID(74), flags: TileFlags(128) },
        Cell { id: TileID(81), flags: TileFlags(0) },
        Cell { id: TileID(67), flags: TileFlags(0) },
        Cell { id: TileID(67), flags: TileFlags(0) },
        Cell { id: TileID(67), flags: TileFlags(0) },
        Cell { id: TileID(67), flags: TileFlags(0) },
        Cell { id: TileID(67), flags: TileFlags(0) },
    ],
};

pub const FONT_TILES: [Tile<2>; 82] = [
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 84] },
            Cluster { data: [85, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [5, 64] },
            Cluster { data: [21, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [80, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [1, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [21, 0] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [80, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [5, 80] },
            Cluster { data: [0, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [5, 80] },
            Cluster { data: [17, 80] },
            Cluster { data: [65, 80] },
            Cluster { data: [85, 84] },
            Cluster { data: [1, 80] },
            Cluster { data: [1, 80] },
            Cluster { data: [5, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 84] },
            Cluster { data: [80, 0] },
            Cluster { data: [80, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [1, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [1, 80] },
            Cluster { data: [21, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 84] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 84] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 64] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 84] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 64] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 84] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 84] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 84] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [5, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 20] },
            Cluster { data: [84, 80] },
            Cluster { data: [85, 64] },
            Cluster { data: [85, 0] },
            Cluster { data: [85, 64] },
            Cluster { data: [84, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 4] },
            Cluster { data: [85, 20] },
            Cluster { data: [85, 84] },
            Cluster { data: [84, 68] },
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 4] },
            Cluster { data: [85, 4] },
            Cluster { data: [85, 68] },
            Cluster { data: [84, 84] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [85, 68] },
            Cluster { data: [84, 84] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 20] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [85, 64] },
            Cluster { data: [84, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 0] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 84] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [21, 16] },
            Cluster { data: [5, 64] },
            Cluster { data: [1, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 68] },
            Cluster { data: [84, 68] },
            Cluster { data: [84, 68] },
            Cluster { data: [84, 68] },
            Cluster { data: [84, 68] },
            Cluster { data: [84, 68] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [21, 16] },
            Cluster { data: [5, 64] },
            Cluster { data: [21, 16] },
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [21, 20] },
            Cluster { data: [5, 80] },
            Cluster { data: [1, 64] },
            Cluster { data: [1, 64] },
            Cluster { data: [1, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 80] },
            Cluster { data: [1, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [21, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [80, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 84] },
            Cluster { data: [85, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 84] },
            Cluster { data: [84, 0] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 84] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [21, 80] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 84] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [85, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 80] },
            Cluster { data: [85, 64] },
            Cluster { data: [84, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [85, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [81, 20] },
            Cluster { data: [81, 20] },
            Cluster { data: [81, 20] },
            Cluster { data: [81, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 84] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [84, 84] },
            Cluster { data: [85, 64] },
            Cluster { data: [85, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 84] },
            Cluster { data: [84, 0] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 84] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [5, 64] },
            Cluster { data: [85, 84] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [80, 20] },
            Cluster { data: [80, 20] },
            Cluster { data: [20, 80] },
            Cluster { data: [20, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [81, 20] },
            Cluster { data: [81, 20] },
            Cluster { data: [81, 20] },
            Cluster { data: [81, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [80, 20] },
            Cluster { data: [20, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [21, 80] },
            Cluster { data: [84, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [5, 80] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 84] },
            Cluster { data: [1, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [21, 0] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [1, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 84] },
            Cluster { data: [1, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [21, 0] },
            Cluster { data: [5, 64] },
            Cluster { data: [1, 80] },
            Cluster { data: [0, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 80] },
            Cluster { data: [5, 80] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 80] },
            Cluster { data: [5, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [80, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [1, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [20, 80] },
            Cluster { data: [20, 80] },
            Cluster { data: [4, 16] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [20, 80] },
            Cluster { data: [85, 84] },
            Cluster { data: [20, 80] },
            Cluster { data: [20, 80] },
            Cluster { data: [85, 84] },
            Cluster { data: [20, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [4, 64] },
            Cluster { data: [21, 84] },
            Cluster { data: [84, 64] },
            Cluster { data: [21, 80] },
            Cluster { data: [4, 84] },
            Cluster { data: [85, 80] },
            Cluster { data: [4, 64] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [20, 20] },
            Cluster { data: [20, 80] },
            Cluster { data: [1, 64] },
            Cluster { data: [5, 0] },
            Cluster { data: [20, 80] },
            Cluster { data: [80, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 0] },
            Cluster { data: [80, 64] },
            Cluster { data: [84, 64] },
            Cluster { data: [21, 68] },
            Cluster { data: [81, 80] },
            Cluster { data: [80, 80] },
            Cluster { data: [21, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [80, 0] },
            Cluster { data: [20, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [1, 64] },
            Cluster { data: [0, 80] },
            Cluster { data: [0, 20] },
            Cluster { data: [0, 5] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [1, 80] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [1, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [1, 64] },
            Cluster { data: [17, 68] },
            Cluster { data: [5, 80] },
            Cluster { data: [5, 80] },
            Cluster { data: [17, 68] },
            Cluster { data: [1, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [1, 64] },
            Cluster { data: [1, 64] },
            Cluster { data: [21, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [1, 64] },
            Cluster { data: [1, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [1, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 85] },
            Cluster { data: [0, 0] },
        ],
    },
];
