[package]
name = "tato_layout"
version = "0.3.3"
edition = "2024"
description = "Minimalist and allocation free GUI Layout"
license = "MIT"
repository = "https://github.com/DoctorWhoof/tato_layout"
documentation = "https://docs.rs/tato_layout/latest/tato_layout/"
categories = ["no-std"]

[workspace]
members = ["example_basic", "example_mquad", "example_sdl"]

[dependencies]
tato_math = { path = "../tato_math" }
