[package]
name = "tato"
version = "0.2.0"
edition = "2024"
license = "MIT"
description = "A ridiculously obsolete collection of zero-dependency game development modules that can run on any computer, even potato-powered ones!"
repository = "https://github.com/DoctorWhoof/tato"
readme = "readme.md"

[dependencies]
tato_video = "0.1.21"
tato_pad = "0.2.5"

[workspace]
members = [ "examples/videochip"]
