[package]
name = "tato"
version = "0.2.2"
edition = "2024"
license = "MIT"
description = "A ridiculously obsolete collection of zero-dependency game development modules that can run on any computer, even potato-powered ones!"
repository = "https://github.com/DoctorWhoof/tato"
categories = ["no-std"]

[dependencies]
tato_pad = "0.2.5"
tato_layout = "0.3.21"
tato_audio = { path = "../tato_audio" }
tato_video = { path = "../tato_video" }
# tato_pipe = { path = "../tato_pipe" }

[build-dependencies]
# tato_pipe = { path = "../tato_pipe" }

[workspace]
members = [
    "examples/scenes",
    "examples/audio",
    "examples/pipe",
    "examples/font", "examples/layers",
]
