[package]
name = "spud"
version = "0.1.0"
edition = "2021"

[features]
std = []

[workspace]
members = ["test_collisions", "test_bricks", "template_mquad"]

[profile.release]
# debug = true
panic = "abort"
# These settings will increase compile times in release mode!
strip = true
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
libm = "0.2.8"
num-traits = { version = "0.2.18" }
slotmap = { version = "1.0.7", default-features = false }
