[package]
name = "tato"
version = "0.1.4"
edition = "2021"
license = "MIT"
description = "A ridiculous, obsolete engine that aims to run very well on any computer. Even potato powered ones!"
repository = "https://github.com/DoctorWhoof/tato"
readme = "readme.md"

[features]
std = []

[workspace]
members = [
    "test_collisions",
    "test_bugs",
    "test_bricks",
    "test_pattern",
    "tato_mquad",
]

[profile.release]
# debug = true
panic = "abort"
# These settings are likely to increase compile times in release mode!
strip = true
lto = true
opt-level = 3
codegen-units = 1

[dependencies]
# libm = "0.2.8"
num-traits = { version = "0.2.18" }
slotmap = { version = "1.0.7", default-features = false }
