[package]
name = "tato"
version = "0.2.2"
edition = "2024"
license = "MIT"
description = "A ridiculously obsolete collection of zero-dependency game development modules that can run on any computer, even potato-powered ones!"
repository = "https://github.com/DoctorWhoof/tato"
categories = ["no-std"]

[dependencies]
tato_pad = { path = "../tato_pad" }
tato_layout = { path = "../tato_layout" }
tato_audio = { path = "../tato_audio" }
tato_video = { path = "../tato_video" }
tato_math = { path = "../tato_math" }
smooth-buffer = { path = "../smooth_buffer" }
# tato_arena = { path = "../tato_arena" }

[build-dependencies]
tato_pipe = { path = "../tato_pipe" }

[workspace]
members = [
    "examples/scenes",
    "examples/audio",
    "examples/font",
    "examples/tilemap",
    "examples/palette_save",
    # "examples/pipe",
]
