[package]
name = "audio"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = {version = "0.9.0" }
tato = { path = "../../"}
backend_cpal = { path = "../../crates/backend_cpal"}
tato_raylib = { path = "../../crates/backend_raylib"}
tato_dashboard = { path = "../../crates/dashboard" }
