[package]
name = "test_bricks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.4"
tato = "0.1.1"

[build-dependencies]
tato = "0.1.1"
tato_pipe = "0.1.1"
