[package]
name = "tilemap"
version = "0.1.0"
edition = "2024"

[dependencies]
tato = { path = "../../" }
tato_raylib = { path = "../../../tato_raylib"}

[build-dependencies]
tato_pipe = { path = "../../../tato_pipe" }
