[package]
name = "tato_winit"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30"
wgpu = { version = "22.1", features = ["wgsl"] }
pollster = "0.3"
bytemuck = { version = "1.18", features = ["derive"] }
tato = { path = "../../" }

[features]
default = []

