// Auto-generated code. Do not edit manually!
#![allow(unused)]
use tato::prelude::*;

pub const ASTRO_TILESET: TilesetData = TilesetData {
    tiles: &ASTRO_TILES,
    colors: Some(&ASTRO_COLORS),
    sub_palettes: Some(&[&ASTRO_SUBPALETTE_0, &ASTRO_SUBPALETTE_1]),
};

pub const ASTRO_COLORS: [RGBA12; 4] = [
    RGBA12::with_transparency(0, 0, 0, 0),
    RGBA12::with_transparency(7, 7, 7, 7),
    RGBA12::with_transparency(0, 0, 0, 7),
    RGBA12::with_transparency(1, 1, 6, 7),
];

pub const ASTRO_SUBPALETTE_0: [u8; 4] = [0, 1, 2, 0];

pub const ASTRO_SUBPALETTE_1: [u8; 4] = [0, 1, 2, 3];

pub const STRIP_ASTRO: [Tilemap<4>; 24] = [
    Tilemap {
        cells: [
            Cell {
                id: TileID(0),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(0),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(1),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(1),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(2),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(2),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(3),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(3),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(4),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(5),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(6),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(6),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(0),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(0),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(1),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(1),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(7),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(7),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(8),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(9),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(0),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(0),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(1),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(1),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(7),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(7),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(9),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(8),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(2),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(2),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(3),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(3),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(10),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(10),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(11),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(12),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(2),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(2),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(13),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(13),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(10),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(10),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(12),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(11),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(4),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(5),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(6),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(6),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(10),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(14),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(15),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(16),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(4),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(5),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(6),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(6),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(10),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(14),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(17),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(18),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(19),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(19),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(20),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
            Cell {
                id: TileID(21),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(22),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(22),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(23),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
            Cell {
                id: TileID(24),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(19),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(19),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(25),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
            Cell {
                id: TileID(26),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(19),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(19),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(27),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
            Cell {
                id: TileID(28),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(29),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(29),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(30),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
            Cell {
                id: TileID(31),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(29),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(29),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(32),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
            Cell {
                id: TileID(33),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(22),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(22),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(34),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
            Cell {
                id: TileID(35),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(29),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(29),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(36),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
            Cell {
                id: TileID(37),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
    Tilemap {
        cells: [
            Cell {
                id: TileID(19),
                flags: TileFlags(0),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(19),
                flags: TileFlags(128),
                sub_palette: PaletteID(0),
                group: 0,
            },
            Cell {
                id: TileID(38),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
            Cell {
                id: TileID(39),
                flags: TileFlags(0),
                sub_palette: PaletteID(1),
                group: 0,
            },
        ],
        columns: 2,
        rows: 2,
    },
];

pub const ASTRO_TILES: [Tile<2>; 40] = [
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 89] },
            Cluster { data: [0, 89] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 21] },
            Cluster { data: [0, 64] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 69] },
            Cluster { data: [0, 69] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 21] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [0, 85] },
            Cluster { data: [0, 21] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 64] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [0, 85] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 20] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 0] },
            Cluster { data: [85, 64] },
            Cluster { data: [85, 64] },
            Cluster { data: [86, 64] },
            Cluster { data: [86, 64] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 85] },
            Cluster { data: [0, 5] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 17] },
            Cluster { data: [0, 17] },
            Cluster { data: [0, 20] },
            Cluster { data: [0, 5] },
            Cluster { data: [0, 1] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 89] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 89] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 64] },
            Cluster { data: [1, 81] },
            Cluster { data: [1, 81] },
            Cluster { data: [0, 69] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [101, 0] },
            Cluster { data: [84, 64] },
            Cluster { data: [1, 64] },
            Cluster { data: [85, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [20, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [0, 85] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 21] },
            Cluster { data: [0, 64] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [0, 85] },
            Cluster { data: [0, 5] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 64] },
            Cluster { data: [1, 64] },
            Cluster { data: [85, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [20, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [1, 64] },
            Cluster { data: [1, 85] },
            Cluster { data: [0, 85] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 20] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 0] },
            Cluster { data: [85, 64] },
            Cluster { data: [85, 64] },
            Cluster { data: [86, 64] },
            Cluster { data: [86, 64] },
            Cluster { data: [85, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 5] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 20] },
            Cluster { data: [1, 65] },
            Cluster { data: [0, 5] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [80, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [21, 0] },
            Cluster { data: [85, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 5] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 4] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [0, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [80, 0] },
            Cluster { data: [68, 0] },
            Cluster { data: [81, 0] },
            Cluster { data: [81, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [84, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 85] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 89] },
            Cluster { data: [15, 89] },
            Cluster { data: [3, 255] },
            Cluster { data: [0, 63] },
            Cluster { data: [3, 195] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 64] },
            Cluster { data: [85, 64] },
            Cluster { data: [85, 64] },
            Cluster { data: [101, 64] },
            Cluster { data: [101, 240] },
            Cluster { data: [255, 192] },
            Cluster { data: [195, 240] },
            Cluster { data: [240, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [15, 85] },
            Cluster { data: [3, 255] },
            Cluster { data: [0, 63] },
            Cluster { data: [15, 3] },
            Cluster { data: [0, 15] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 64] },
            Cluster { data: [85, 64] },
            Cluster { data: [85, 64] },
            Cluster { data: [85, 240] },
            Cluster { data: [255, 192] },
            Cluster { data: [255, 240] },
            Cluster { data: [252, 0] },
            Cluster { data: [240, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [13, 85] },
            Cluster { data: [63, 255] },
            Cluster { data: [0, 255] },
            Cluster { data: [0, 3] },
            Cluster { data: [0, 63] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 64] },
            Cluster { data: [85, 64] },
            Cluster { data: [86, 64] },
            Cluster { data: [86, 112] },
            Cluster { data: [255, 252] },
            Cluster { data: [255, 192] },
            Cluster { data: [252, 240] },
            Cluster { data: [192, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [1, 85] },
            Cluster { data: [49, 85] },
            Cluster { data: [13, 85] },
            Cluster { data: [13, 89] },
            Cluster { data: [15, 89] },
            Cluster { data: [3, 255] },
            Cluster { data: [0, 15] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 64] },
            Cluster { data: [85, 76] },
            Cluster { data: [85, 124] },
            Cluster { data: [101, 112] },
            Cluster { data: [101, 240] },
            Cluster { data: [255, 192] },
            Cluster { data: [252, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 85] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [1, 89] },
            Cluster { data: [13, 89] },
            Cluster { data: [15, 85] },
            Cluster { data: [3, 255] },
            Cluster { data: [0, 63] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 64] },
            Cluster { data: [85, 64] },
            Cluster { data: [101, 64] },
            Cluster { data: [101, 112] },
            Cluster { data: [85, 240] },
            Cluster { data: [255, 192] },
            Cluster { data: [192, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [13, 85] },
            Cluster { data: [15, 85] },
            Cluster { data: [3, 255] },
            Cluster { data: [0, 63] },
            Cluster { data: [0, 3] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 64] },
            Cluster { data: [85, 64] },
            Cluster { data: [85, 112] },
            Cluster { data: [85, 240] },
            Cluster { data: [255, 192] },
            Cluster { data: [255, 0] },
            Cluster { data: [240, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [1, 85] },
            Cluster { data: [13, 85] },
            Cluster { data: [13, 85] },
            Cluster { data: [3, 85] },
            Cluster { data: [0, 255] },
            Cluster { data: [0, 15] },
            Cluster { data: [0, 3] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 64] },
            Cluster { data: [85, 112] },
            Cluster { data: [85, 112] },
            Cluster { data: [85, 192] },
            Cluster { data: [255, 192] },
            Cluster { data: [252, 0] },
            Cluster { data: [240, 0] },
            Cluster { data: [192, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [13, 85] },
            Cluster { data: [63, 85] },
            Cluster { data: [15, 255] },
            Cluster { data: [0, 255] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 64] },
            Cluster { data: [86, 64] },
            Cluster { data: [86, 112] },
            Cluster { data: [85, 192] },
            Cluster { data: [255, 0] },
            Cluster { data: [252, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [1, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [61, 85] },
            Cluster { data: [255, 85] },
            Cluster { data: [15, 255] },
            Cluster { data: [0, 255] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 64] },
            Cluster { data: [85, 64] },
            Cluster { data: [86, 112] },
            Cluster { data: [86, 252] },
            Cluster { data: [255, 192] },
            Cluster { data: [240, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
];
