// Auto-generated code - do not edit manually
use tato::prelude::*;

pub const PATCH_TILESET: TilesetData = TilesetData {
    tiles: &PATCH_TILES,
    colors: Some(&PATCH_COLORS),
    sub_palettes: Some(&[
        &PATCH_SUBPALETTE_0,
        &PATCH_SUBPALETTE_1,
        &PATCH_SUBPALETTE_2,
        &PATCH_SUBPALETTE_3,
        &PATCH_SUBPALETTE_4,
        &PATCH_SUBPALETTE_5,
        &PATCH_SUBPALETTE_6,
        &PATCH_SUBPALETTE_7,
        &PATCH_SUBPALETTE_8,
        &PATCH_SUBPALETTE_9,
        &PATCH_SUBPALETTE_10,
        &PATCH_SUBPALETTE_11,
    ]),
};

pub const PATCH_COLORS: [RGBA12; 15] = [
    RGBA12::new(0, 0, 0, 0),
    RGBA12::new(5, 5, 6, 7),
    RGBA12::new(3, 3, 3, 7),
    RGBA12::new(1, 1, 2, 7),
    RGBA12::new(7, 7, 2, 7),
    RGBA12::new(7, 4, 6, 7),
    RGBA12::new(3, 6, 7, 7),
    RGBA12::new(3, 6, 2, 7),
    RGBA12::new(7, 6, 5, 7),
    RGBA12::new(0, 0, 0, 7),
    RGBA12::new(7, 4, 1, 7),
    RGBA12::new(3, 3, 7, 7),
    RGBA12::new(2, 2, 4, 7),
    RGBA12::new(3, 2, 2, 7),
    RGBA12::new(4, 2, 4, 7),
];

pub const PATCH_SUBPALETTE_0: [u8; 4] = [0, 1, 2, 0];

pub const PATCH_SUBPALETTE_1: [u8; 4] = [0, 1, 2, 3];

pub const PATCH_SUBPALETTE_2: [u8; 4] = [2, 4, 9, 0];

pub const PATCH_SUBPALETTE_3: [u8; 4] = [2, 5, 9, 0];

pub const PATCH_SUBPALETTE_4: [u8; 4] = [2, 6, 9, 0];

pub const PATCH_SUBPALETTE_5: [u8; 4] = [2, 7, 9, 0];

pub const PATCH_SUBPALETTE_6: [u8; 4] = [2, 8, 9, 0];

pub const PATCH_SUBPALETTE_7: [u8; 4] = [2, 9, 10, 0];

pub const PATCH_SUBPALETTE_8: [u8; 4] = [2, 9, 11, 0];

pub const PATCH_SUBPALETTE_9: [u8; 4] = [2, 9, 12, 0];

pub const PATCH_SUBPALETTE_10: [u8; 4] = [2, 9, 13, 0];

pub const PATCH_SUBPALETTE_11: [u8; 4] = [2, 9, 14, 0];

pub const PATCH_MAP: BGMap<9> = BGMap {
    cells: [
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(0) },
        Cell { id: TileID(2), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(96) },
        Cell { id: TileID(3), flags: TileFlags(0) },
        Cell { id: TileID(4), flags: TileFlags(1) },
        Cell { id: TileID(2), flags: TileFlags(97) },
        Cell { id: TileID(4), flags: TileFlags(225) },
        Cell { id: TileID(5), flags: TileFlags(1) },
    ],
    columns: 3,
    rows: 3,
};

pub const SMILEYS_MAP: BGMap<160> = BGMap {
    cells: [
        Cell { id: TileID(6), flags: TileFlags(1) },
        Cell { id: TileID(7), flags: TileFlags(1) },
        Cell { id: TileID(7), flags: TileFlags(129) },
        Cell { id: TileID(7), flags: TileFlags(129) },
        Cell { id: TileID(7), flags: TileFlags(129) },
        Cell { id: TileID(7), flags: TileFlags(129) },
        Cell { id: TileID(7), flags: TileFlags(129) },
        Cell { id: TileID(7), flags: TileFlags(129) },
        Cell { id: TileID(7), flags: TileFlags(129) },
        Cell { id: TileID(7), flags: TileFlags(129) },
        Cell { id: TileID(7), flags: TileFlags(129) },
        Cell { id: TileID(7), flags: TileFlags(129) },
        Cell { id: TileID(7), flags: TileFlags(129) },
        Cell { id: TileID(7), flags: TileFlags(129) },
        Cell { id: TileID(7), flags: TileFlags(129) },
        Cell { id: TileID(6), flags: TileFlags(225) },
        Cell { id: TileID(7), flags: TileFlags(97) },
        Cell { id: TileID(8), flags: TileFlags(2) },
        Cell { id: TileID(8), flags: TileFlags(130) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(8), flags: TileFlags(3) },
        Cell { id: TileID(8), flags: TileFlags(131) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(8), flags: TileFlags(4) },
        Cell { id: TileID(8), flags: TileFlags(132) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(8), flags: TileFlags(5) },
        Cell { id: TileID(8), flags: TileFlags(133) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(8), flags: TileFlags(6) },
        Cell { id: TileID(8), flags: TileFlags(134) },
        Cell { id: TileID(7), flags: TileFlags(225) },
        Cell { id: TileID(7), flags: TileFlags(97) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(9), flags: TileFlags(130) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(9), flags: TileFlags(3) },
        Cell { id: TileID(9), flags: TileFlags(131) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(9), flags: TileFlags(4) },
        Cell { id: TileID(9), flags: TileFlags(132) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(9), flags: TileFlags(5) },
        Cell { id: TileID(9), flags: TileFlags(133) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(9), flags: TileFlags(6) },
        Cell { id: TileID(9), flags: TileFlags(134) },
        Cell { id: TileID(7), flags: TileFlags(225) },
        Cell { id: TileID(7), flags: TileFlags(97) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(7), flags: TileFlags(225) },
        Cell { id: TileID(7), flags: TileFlags(97) },
        Cell { id: TileID(10), flags: TileFlags(7) },
        Cell { id: TileID(10), flags: TileFlags(135) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(10), flags: TileFlags(8) },
        Cell { id: TileID(10), flags: TileFlags(136) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(10), flags: TileFlags(9) },
        Cell { id: TileID(10), flags: TileFlags(137) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(10), flags: TileFlags(10) },
        Cell { id: TileID(10), flags: TileFlags(138) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(10), flags: TileFlags(11) },
        Cell { id: TileID(10), flags: TileFlags(139) },
        Cell { id: TileID(7), flags: TileFlags(225) },
        Cell { id: TileID(7), flags: TileFlags(97) },
        Cell { id: TileID(11), flags: TileFlags(7) },
        Cell { id: TileID(11), flags: TileFlags(135) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(11), flags: TileFlags(8) },
        Cell { id: TileID(11), flags: TileFlags(136) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(11), flags: TileFlags(9) },
        Cell { id: TileID(11), flags: TileFlags(137) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(11), flags: TileFlags(10) },
        Cell { id: TileID(11), flags: TileFlags(138) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(11), flags: TileFlags(11) },
        Cell { id: TileID(11), flags: TileFlags(139) },
        Cell { id: TileID(7), flags: TileFlags(225) },
        Cell { id: TileID(7), flags: TileFlags(97) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(7), flags: TileFlags(225) },
        Cell { id: TileID(7), flags: TileFlags(97) },
        Cell { id: TileID(8), flags: TileFlags(2) },
        Cell { id: TileID(8), flags: TileFlags(130) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(8), flags: TileFlags(2) },
        Cell { id: TileID(8), flags: TileFlags(130) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(8), flags: TileFlags(2) },
        Cell { id: TileID(8), flags: TileFlags(130) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(8), flags: TileFlags(2) },
        Cell { id: TileID(8), flags: TileFlags(130) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(8), flags: TileFlags(2) },
        Cell { id: TileID(8), flags: TileFlags(130) },
        Cell { id: TileID(7), flags: TileFlags(225) },
        Cell { id: TileID(7), flags: TileFlags(97) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(9), flags: TileFlags(130) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(9), flags: TileFlags(130) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(9), flags: TileFlags(130) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(9), flags: TileFlags(130) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(9), flags: TileFlags(130) },
        Cell { id: TileID(7), flags: TileFlags(225) },
        Cell { id: TileID(6), flags: TileFlags(65) },
        Cell { id: TileID(7), flags: TileFlags(193) },
        Cell { id: TileID(7), flags: TileFlags(193) },
        Cell { id: TileID(7), flags: TileFlags(193) },
        Cell { id: TileID(7), flags: TileFlags(193) },
        Cell { id: TileID(7), flags: TileFlags(193) },
        Cell { id: TileID(7), flags: TileFlags(193) },
        Cell { id: TileID(7), flags: TileFlags(193) },
        Cell { id: TileID(7), flags: TileFlags(193) },
        Cell { id: TileID(7), flags: TileFlags(193) },
        Cell { id: TileID(7), flags: TileFlags(193) },
        Cell { id: TileID(7), flags: TileFlags(193) },
        Cell { id: TileID(7), flags: TileFlags(193) },
        Cell { id: TileID(7), flags: TileFlags(193) },
        Cell { id: TileID(7), flags: TileFlags(193) },
        Cell { id: TileID(6), flags: TileFlags(193) },
    ],
    columns: 16,
    rows: 10,
};

pub const PATCH_TILES: [Tile<2>; 12] = [
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 170] },
            Cluster { data: [6, 170] },
            Cluster { data: [6, 170] },
            Cluster { data: [6, 170] },
            Cluster { data: [6, 170] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 85] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 0] },
            Cluster { data: [170, 64] },
            Cluster { data: [170, 144] },
            Cluster { data: [170, 156] },
            Cluster { data: [170, 159] },
            Cluster { data: [170, 159] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [170, 159] },
            Cluster { data: [170, 159] },
            Cluster { data: [170, 159] },
            Cluster { data: [170, 159] },
            Cluster { data: [170, 159] },
            Cluster { data: [170, 159] },
            Cluster { data: [170, 159] },
            Cluster { data: [170, 159] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [170, 159] },
            Cluster { data: [170, 159] },
            Cluster { data: [170, 159] },
            Cluster { data: [170, 159] },
            Cluster { data: [170, 127] },
            Cluster { data: [85, 255] },
            Cluster { data: [255, 252] },
            Cluster { data: [255, 240] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [255, 255] },
            Cluster { data: [255, 255] },
            Cluster { data: [255, 255] },
            Cluster { data: [255, 254] },
            Cluster { data: [255, 234] },
            Cluster { data: [255, 170] },
            Cluster { data: [255, 170] },
            Cluster { data: [254, 170] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [255, 255] },
            Cluster { data: [255, 255] },
            Cluster { data: [255, 255] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 5] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [5, 85] },
            Cluster { data: [5, 101] },
            Cluster { data: [21, 101] },
            Cluster { data: [21, 101] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 85] },
            Cluster { data: [21, 170] },
            Cluster { data: [5, 170] },
            Cluster { data: [5, 106] },
            Cluster { data: [1, 90] },
            Cluster { data: [0, 85] },
            Cluster { data: [0, 5] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 10] },
            Cluster { data: [0, 170] },
            Cluster { data: [2, 170] },
            Cluster { data: [10, 170] },
            Cluster { data: [10, 154] },
            Cluster { data: [42, 154] },
            Cluster { data: [42, 154] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [42, 170] },
            Cluster { data: [42, 85] },
            Cluster { data: [10, 85] },
            Cluster { data: [10, 149] },
            Cluster { data: [2, 165] },
            Cluster { data: [0, 170] },
            Cluster { data: [0, 10] },
            Cluster { data: [0, 0] },
        ],
    },
];
