// Auto-generated code. Do not edit manually!
use tato::prelude::*;

pub const SMILEYS_TILESET: TilesetData = TilesetData {
    tiles: Some(&SMILEYS_TILES),
    colors: Some(&SMILEYS_COLORS),
    sub_palettes: Some(&[
        &SMILEYS_SUBPALETTE_0,
        &SMILEYS_SUBPALETTE_1,
        &SMILEYS_SUBPALETTE_2,
        &SMILEYS_SUBPALETTE_3,
        &SMILEYS_SUBPALETTE_4,
        &SMILEYS_SUBPALETTE_5,
        &SMILEYS_SUBPALETTE_6,
        &SMILEYS_SUBPALETTE_7,
        &SMILEYS_SUBPALETTE_8,
        &SMILEYS_SUBPALETTE_9,
        &SMILEYS_SUBPALETTE_10,
    ]),
};

pub const SMILEYS_COLORS: [RGBA12; 12] = [
    RGBA12::with_transparency(7, 7, 7, 7),
    RGBA12::with_transparency(4, 4, 4, 7),
    RGBA12::with_transparency(7, 6, 3, 7),
    RGBA12::with_transparency(0, 2, 1, 7),
    RGBA12::with_transparency(0, 1, 3, 7),
    RGBA12::with_transparency(0, 0, 0, 7),
    RGBA12::with_transparency(6, 4, 1, 7),
    RGBA12::with_transparency(2, 4, 2, 7),
    RGBA12::with_transparency(1, 2, 6, 7),
    RGBA12::with_transparency(6, 3, 6, 7),
    RGBA12::with_transparency(4, 6, 3, 7),
    RGBA12::with_transparency(4, 6, 7, 7),
];

pub const SMILEYS_SUBPALETTE_0: [u8; 4] = [0, 1, 0, 0];

pub const SMILEYS_SUBPALETTE_1: [u8; 4] = [1, 2, 5, 0];

pub const SMILEYS_SUBPALETTE_2: [u8; 4] = [1, 0, 0, 0];

pub const SMILEYS_SUBPALETTE_3: [u8; 4] = [1, 3, 5, 0];

pub const SMILEYS_SUBPALETTE_4: [u8; 4] = [1, 4, 5, 0];

pub const SMILEYS_SUBPALETTE_5: [u8; 4] = [1, 6, 5, 0];

pub const SMILEYS_SUBPALETTE_6: [u8; 4] = [1, 7, 5, 0];

pub const SMILEYS_SUBPALETTE_7: [u8; 4] = [1, 8, 5, 0];

pub const SMILEYS_SUBPALETTE_8: [u8; 4] = [1, 9, 5, 0];

pub const SMILEYS_SUBPALETTE_9: [u8; 4] = [1, 10, 5, 0];

pub const SMILEYS_SUBPALETTE_10: [u8; 4] = [1, 11, 5, 0];

pub const SMILEYS_MAP: Tilemap<160> = Tilemap {
    columns: 16,
    rows: 10,
    cells: [
        Cell {
            id: TileID(0),
            flags: TileFlags(0),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(0),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(0),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(0),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(0),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(0),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(0),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(0),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(0),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(0),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(0),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(0),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(0),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(0),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(0),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(0),
            flags: TileFlags(128),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(32),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(0),
            sub_palette: PaletteID(1),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(128),
            sub_palette: PaletteID(1),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(0),
            sub_palette: PaletteID(3),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(128),
            sub_palette: PaletteID(3),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(0),
            sub_palette: PaletteID(4),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(128),
            sub_palette: PaletteID(4),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(0),
            sub_palette: PaletteID(3),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(128),
            sub_palette: PaletteID(3),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(0),
            sub_palette: PaletteID(1),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(128),
            sub_palette: PaletteID(1),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(32),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(0),
            sub_palette: PaletteID(1),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(128),
            sub_palette: PaletteID(1),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(0),
            sub_palette: PaletteID(3),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(128),
            sub_palette: PaletteID(3),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(0),
            sub_palette: PaletteID(4),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(128),
            sub_palette: PaletteID(4),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(0),
            sub_palette: PaletteID(3),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(128),
            sub_palette: PaletteID(3),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(0),
            sub_palette: PaletteID(1),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(128),
            sub_palette: PaletteID(1),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(32),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(32),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(0),
            sub_palette: PaletteID(5),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(128),
            sub_palette: PaletteID(5),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(0),
            sub_palette: PaletteID(6),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(128),
            sub_palette: PaletteID(6),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(0),
            sub_palette: PaletteID(7),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(128),
            sub_palette: PaletteID(7),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(0),
            sub_palette: PaletteID(6),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(128),
            sub_palette: PaletteID(6),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(0),
            sub_palette: PaletteID(5),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(128),
            sub_palette: PaletteID(5),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(32),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(0),
            sub_palette: PaletteID(5),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(128),
            sub_palette: PaletteID(5),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(0),
            sub_palette: PaletteID(6),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(128),
            sub_palette: PaletteID(6),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(0),
            sub_palette: PaletteID(7),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(128),
            sub_palette: PaletteID(7),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(0),
            sub_palette: PaletteID(6),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(128),
            sub_palette: PaletteID(6),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(0),
            sub_palette: PaletteID(5),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(128),
            sub_palette: PaletteID(5),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(32),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(32),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(0),
            sub_palette: PaletteID(8),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(128),
            sub_palette: PaletteID(8),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(0),
            sub_palette: PaletteID(9),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(128),
            sub_palette: PaletteID(9),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(0),
            sub_palette: PaletteID(10),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(128),
            sub_palette: PaletteID(10),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(0),
            sub_palette: PaletteID(9),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(128),
            sub_palette: PaletteID(9),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(0),
            sub_palette: PaletteID(8),
            group: 0,
        },
        Cell {
            id: TileID(2),
            flags: TileFlags(128),
            sub_palette: PaletteID(8),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(1),
            flags: TileFlags(32),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(0),
            sub_palette: PaletteID(8),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(128),
            sub_palette: PaletteID(8),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(0),
            sub_palette: PaletteID(9),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(128),
            sub_palette: PaletteID(9),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(0),
            sub_palette: PaletteID(10),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(128),
            sub_palette: PaletteID(10),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(0),
            sub_palette: PaletteID(9),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(128),
            sub_palette: PaletteID(9),
            group: 0,
        },
        Cell {
            id: TileID(3),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(0),
            sub_palette: PaletteID(8),
            group: 0,
        },
        Cell {
            id: TileID(5),
            flags: TileFlags(128),
            sub_palette: PaletteID(8),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(0),
            flags: TileFlags(32),
            sub_palette: PaletteID(0),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(96),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(96),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(96),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(96),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(96),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(96),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(96),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(96),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(96),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(96),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(96),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(96),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(96),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(4),
            flags: TileFlags(96),
            sub_palette: PaletteID(2),
            group: 0,
        },
        Cell {
            id: TileID(6),
            flags: TileFlags(0),
            sub_palette: PaletteID(2),
            group: 0,
        },
    ],
};

pub const SMILEYS_TILES: [Tile<2>; 7] = [
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 1] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 85] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 85] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 5] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [5, 85] },
            Cluster { data: [5, 101] },
            Cluster { data: [21, 101] },
            Cluster { data: [21, 101] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 21] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 21] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 85] },
            Cluster { data: [21, 170] },
            Cluster { data: [5, 170] },
            Cluster { data: [5, 106] },
            Cluster { data: [1, 90] },
            Cluster { data: [0, 85] },
            Cluster { data: [0, 5] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 21] },
            Cluster { data: [0, 85] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [21, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
        ],
    },
];
