// Auto-generated code - do not edit manually
use tato::prelude::*;

pub const SMILEYS_TILESET: TilesetData = TilesetData {
    tiles: &SMILEYS_TILES,
    colors: Some(&SMILEYS_COLORS),
    sub_palettes: Some(&[
        &SMILEYS_SUBPALETTE_0,
        &SMILEYS_SUBPALETTE_1,
        &SMILEYS_SUBPALETTE_2,
        &SMILEYS_SUBPALETTE_3,
        &SMILEYS_SUBPALETTE_4,
        &SMILEYS_SUBPALETTE_5,
        &SMILEYS_SUBPALETTE_6,
        &SMILEYS_SUBPALETTE_7,
        &SMILEYS_SUBPALETTE_8,
        &SMILEYS_SUBPALETTE_9,
        &SMILEYS_SUBPALETTE_10,
    ]),
};

pub const SMILEYS_COLORS: [RGBA12; 13] = [
    RGBA12::new(1, 1, 2, 7),
    RGBA12::new(3, 3, 3, 7),
    RGBA12::new(7, 7, 2, 7),
    RGBA12::new(7, 4, 6, 7),
    RGBA12::new(3, 6, 7, 7),
    RGBA12::new(3, 6, 2, 7),
    RGBA12::new(7, 6, 5, 7),
    RGBA12::new(0, 0, 0, 7),
    RGBA12::new(7, 4, 1, 7),
    RGBA12::new(3, 3, 7, 7),
    RGBA12::new(2, 2, 4, 7),
    RGBA12::new(3, 2, 2, 7),
    RGBA12::new(4, 2, 4, 7),
];

pub const SMILEYS_SUBPALETTE_0: [u8; 4] = [0, 1, 0, 0];

pub const SMILEYS_SUBPALETTE_1: [u8; 4] = [1, 2, 7, 0];

pub const SMILEYS_SUBPALETTE_2: [u8; 4] = [1, 3, 7, 0];

pub const SMILEYS_SUBPALETTE_3: [u8; 4] = [1, 4, 7, 0];

pub const SMILEYS_SUBPALETTE_4: [u8; 4] = [1, 5, 7, 0];

pub const SMILEYS_SUBPALETTE_5: [u8; 4] = [1, 6, 7, 0];

pub const SMILEYS_SUBPALETTE_6: [u8; 4] = [1, 7, 8, 0];

pub const SMILEYS_SUBPALETTE_7: [u8; 4] = [1, 7, 9, 0];

pub const SMILEYS_SUBPALETTE_8: [u8; 4] = [1, 7, 10, 0];

pub const SMILEYS_SUBPALETTE_9: [u8; 4] = [1, 7, 11, 0];

pub const SMILEYS_SUBPALETTE_10: [u8; 4] = [1, 7, 12, 0];

pub const SMILEYS_MAP: BGMap<160> = BGMap {
    cells: [
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(128) },
        Cell { id: TileID(1), flags: TileFlags(128) },
        Cell { id: TileID(1), flags: TileFlags(128) },
        Cell { id: TileID(1), flags: TileFlags(128) },
        Cell { id: TileID(1), flags: TileFlags(128) },
        Cell { id: TileID(1), flags: TileFlags(128) },
        Cell { id: TileID(1), flags: TileFlags(128) },
        Cell { id: TileID(1), flags: TileFlags(128) },
        Cell { id: TileID(1), flags: TileFlags(128) },
        Cell { id: TileID(1), flags: TileFlags(128) },
        Cell { id: TileID(1), flags: TileFlags(128) },
        Cell { id: TileID(1), flags: TileFlags(128) },
        Cell { id: TileID(1), flags: TileFlags(128) },
        Cell { id: TileID(0), flags: TileFlags(224) },
        Cell { id: TileID(1), flags: TileFlags(96) },
        Cell { id: TileID(2), flags: TileFlags(1) },
        Cell { id: TileID(2), flags: TileFlags(129) },
        Cell { id: TileID(3), flags: TileFlags(0) },
        Cell { id: TileID(2), flags: TileFlags(2) },
        Cell { id: TileID(2), flags: TileFlags(130) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(2), flags: TileFlags(3) },
        Cell { id: TileID(2), flags: TileFlags(131) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(2), flags: TileFlags(4) },
        Cell { id: TileID(2), flags: TileFlags(132) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(2), flags: TileFlags(5) },
        Cell { id: TileID(2), flags: TileFlags(133) },
        Cell { id: TileID(1), flags: TileFlags(224) },
        Cell { id: TileID(1), flags: TileFlags(96) },
        Cell { id: TileID(4), flags: TileFlags(1) },
        Cell { id: TileID(4), flags: TileFlags(129) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(4), flags: TileFlags(2) },
        Cell { id: TileID(4), flags: TileFlags(130) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(4), flags: TileFlags(3) },
        Cell { id: TileID(4), flags: TileFlags(131) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(4), flags: TileFlags(4) },
        Cell { id: TileID(4), flags: TileFlags(132) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(4), flags: TileFlags(5) },
        Cell { id: TileID(4), flags: TileFlags(133) },
        Cell { id: TileID(1), flags: TileFlags(224) },
        Cell { id: TileID(1), flags: TileFlags(96) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(1), flags: TileFlags(224) },
        Cell { id: TileID(1), flags: TileFlags(96) },
        Cell { id: TileID(5), flags: TileFlags(6) },
        Cell { id: TileID(5), flags: TileFlags(134) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(5), flags: TileFlags(7) },
        Cell { id: TileID(5), flags: TileFlags(135) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(5), flags: TileFlags(8) },
        Cell { id: TileID(5), flags: TileFlags(136) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(5), flags: TileFlags(9) },
        Cell { id: TileID(5), flags: TileFlags(137) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(5), flags: TileFlags(10) },
        Cell { id: TileID(5), flags: TileFlags(138) },
        Cell { id: TileID(1), flags: TileFlags(224) },
        Cell { id: TileID(1), flags: TileFlags(96) },
        Cell { id: TileID(6), flags: TileFlags(6) },
        Cell { id: TileID(6), flags: TileFlags(134) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(6), flags: TileFlags(7) },
        Cell { id: TileID(6), flags: TileFlags(135) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(6), flags: TileFlags(8) },
        Cell { id: TileID(6), flags: TileFlags(136) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(6), flags: TileFlags(9) },
        Cell { id: TileID(6), flags: TileFlags(137) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(6), flags: TileFlags(10) },
        Cell { id: TileID(6), flags: TileFlags(138) },
        Cell { id: TileID(1), flags: TileFlags(224) },
        Cell { id: TileID(1), flags: TileFlags(96) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(1), flags: TileFlags(224) },
        Cell { id: TileID(1), flags: TileFlags(96) },
        Cell { id: TileID(2), flags: TileFlags(1) },
        Cell { id: TileID(2), flags: TileFlags(129) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(2), flags: TileFlags(1) },
        Cell { id: TileID(2), flags: TileFlags(129) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(2), flags: TileFlags(1) },
        Cell { id: TileID(2), flags: TileFlags(129) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(2), flags: TileFlags(1) },
        Cell { id: TileID(2), flags: TileFlags(129) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(2), flags: TileFlags(1) },
        Cell { id: TileID(2), flags: TileFlags(129) },
        Cell { id: TileID(1), flags: TileFlags(224) },
        Cell { id: TileID(1), flags: TileFlags(96) },
        Cell { id: TileID(4), flags: TileFlags(1) },
        Cell { id: TileID(4), flags: TileFlags(129) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(4), flags: TileFlags(1) },
        Cell { id: TileID(4), flags: TileFlags(129) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(4), flags: TileFlags(1) },
        Cell { id: TileID(4), flags: TileFlags(129) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(4), flags: TileFlags(1) },
        Cell { id: TileID(4), flags: TileFlags(129) },
        Cell { id: TileID(3), flags: TileFlags(224) },
        Cell { id: TileID(4), flags: TileFlags(1) },
        Cell { id: TileID(4), flags: TileFlags(129) },
        Cell { id: TileID(1), flags: TileFlags(224) },
        Cell { id: TileID(0), flags: TileFlags(64) },
        Cell { id: TileID(1), flags: TileFlags(192) },
        Cell { id: TileID(1), flags: TileFlags(192) },
        Cell { id: TileID(1), flags: TileFlags(192) },
        Cell { id: TileID(1), flags: TileFlags(192) },
        Cell { id: TileID(1), flags: TileFlags(192) },
        Cell { id: TileID(1), flags: TileFlags(192) },
        Cell { id: TileID(1), flags: TileFlags(192) },
        Cell { id: TileID(1), flags: TileFlags(192) },
        Cell { id: TileID(1), flags: TileFlags(192) },
        Cell { id: TileID(1), flags: TileFlags(192) },
        Cell { id: TileID(1), flags: TileFlags(192) },
        Cell { id: TileID(1), flags: TileFlags(192) },
        Cell { id: TileID(1), flags: TileFlags(192) },
        Cell { id: TileID(1), flags: TileFlags(192) },
        Cell { id: TileID(0), flags: TileFlags(192) },
    ],
    columns: 16,
    rows: 10,
};

pub const SMILEYS_TILES: [Tile<2>; 7] = [
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 1] },
            Cluster { data: [0, 21] },
            Cluster { data: [0, 85] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 85] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 5] },
            Cluster { data: [0, 85] },
            Cluster { data: [1, 85] },
            Cluster { data: [5, 85] },
            Cluster { data: [5, 101] },
            Cluster { data: [21, 101] },
            Cluster { data: [21, 101] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 85] },
            Cluster { data: [21, 170] },
            Cluster { data: [5, 170] },
            Cluster { data: [5, 106] },
            Cluster { data: [1, 90] },
            Cluster { data: [0, 85] },
            Cluster { data: [0, 5] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 10] },
            Cluster { data: [0, 170] },
            Cluster { data: [2, 170] },
            Cluster { data: [10, 170] },
            Cluster { data: [10, 154] },
            Cluster { data: [42, 154] },
            Cluster { data: [42, 154] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [42, 170] },
            Cluster { data: [42, 85] },
            Cluster { data: [10, 85] },
            Cluster { data: [10, 149] },
            Cluster { data: [2, 165] },
            Cluster { data: [0, 170] },
            Cluster { data: [0, 10] },
            Cluster { data: [0, 0] },
        ],
    },
];
