// Auto-generated code - do not edit manually
use tato::prelude::*;

pub const TESTMAP_TILESET: TilesetData = TilesetData {
    tiles: &TESTMAP_TILES,
    colors: Some(&TESTMAP_COLORS),
    sub_palettes: Some(&[
        &TESTMAP_SUBPALETTE_0,
        &TESTMAP_SUBPALETTE_1,
        &TESTMAP_SUBPALETTE_2,
        &TESTMAP_SUBPALETTE_3,
        &TESTMAP_SUBPALETTE_4,
        &TESTMAP_SUBPALETTE_5,
        &TESTMAP_SUBPALETTE_6,
        &TESTMAP_SUBPALETTE_7,
        &TESTMAP_SUBPALETTE_8,
        &TESTMAP_SUBPALETTE_9,
        &TESTMAP_SUBPALETTE_10,
        &TESTMAP_SUBPALETTE_11,
        &TESTMAP_SUBPALETTE_12,
        &TESTMAP_SUBPALETTE_13,
    ]),
};

pub const TESTMAP_COLORS: [RGBA12; 9] = [
    RGBA12::new(0, 0, 0, 7),
    RGBA12::new(0, 1, 2, 7),
    RGBA12::new(1, 2, 3, 7),
    RGBA12::new(0, 0, 1, 7),
    RGBA12::new(1, 1, 3, 7),
    RGBA12::new(6, 5, 0, 7),
    RGBA12::new(7, 7, 7, 7),
    RGBA12::new(0, 2, 3, 7),
    RGBA12::new(0, 1, 1, 7),
];

pub const TESTMAP_SUBPALETTE_0: [u8; 4] = [0, 0, 0, 0];

pub const TESTMAP_SUBPALETTE_1: [u8; 4] = [0, 1, 0, 0];

pub const TESTMAP_SUBPALETTE_2: [u8; 4] = [0, 4, 3, 0];

pub const TESTMAP_SUBPALETTE_3: [u8; 4] = [0, 2, 4, 3];

pub const TESTMAP_SUBPALETTE_4: [u8; 4] = [3, 2, 5, 6];

pub const TESTMAP_SUBPALETTE_5: [u8; 4] = [0, 1, 2, 0];

pub const TESTMAP_SUBPALETTE_6: [u8; 4] = [3, 0, 1, 2];

pub const TESTMAP_SUBPALETTE_7: [u8; 4] = [1, 2, 0, 3];

pub const TESTMAP_SUBPALETTE_8: [u8; 4] = [0, 1, 2, 3];

pub const TESTMAP_SUBPALETTE_9: [u8; 4] = [3, 7, 0, 0];

pub const TESTMAP_SUBPALETTE_10: [u8; 4] = [3, 0, 7, 0];

pub const TESTMAP_SUBPALETTE_11: [u8; 4] = [0, 3, 7, 0];

pub const TESTMAP_SUBPALETTE_12: [u8; 4] = [7, 1, 0, 0];

pub const TESTMAP_SUBPALETTE_13: [u8; 4] = [1, 8, 0, 0];

pub const TEST_MAP: BGMap<972> = BGMap {
    cells: [
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(2), flags: TileFlags(2) },
        Cell { id: TileID(2), flags: TileFlags(2) },
        Cell { id: TileID(3), flags: TileFlags(2) },
        Cell { id: TileID(4), flags: TileFlags(2) },
        Cell { id: TileID(4), flags: TileFlags(2) },
        Cell { id: TileID(5), flags: TileFlags(3) },
        Cell { id: TileID(6), flags: TileFlags(2) },
        Cell { id: TileID(7), flags: TileFlags(4) },
        Cell { id: TileID(7), flags: TileFlags(132) },
        Cell { id: TileID(6), flags: TileFlags(2) },
        Cell { id: TileID(5), flags: TileFlags(3) },
        Cell { id: TileID(6), flags: TileFlags(2) },
        Cell { id: TileID(4), flags: TileFlags(2) },
        Cell { id: TileID(4), flags: TileFlags(2) },
        Cell { id: TileID(3), flags: TileFlags(2) },
        Cell { id: TileID(2), flags: TileFlags(2) },
        Cell { id: TileID(2), flags: TileFlags(2) },
        Cell { id: TileID(2), flags: TileFlags(2) },
        Cell { id: TileID(2), flags: TileFlags(2) },
        Cell { id: TileID(2), flags: TileFlags(2) },
        Cell { id: TileID(2), flags: TileFlags(2) },
        Cell { id: TileID(4), flags: TileFlags(2) },
        Cell { id: TileID(4), flags: TileFlags(2) },
        Cell { id: TileID(6), flags: TileFlags(2) },
        Cell { id: TileID(5), flags: TileFlags(3) },
        Cell { id: TileID(6), flags: TileFlags(2) },
        Cell { id: TileID(7), flags: TileFlags(4) },
        Cell { id: TileID(7), flags: TileFlags(132) },
        Cell { id: TileID(6), flags: TileFlags(2) },
        Cell { id: TileID(6), flags: TileFlags(2) },
        Cell { id: TileID(8), flags: TileFlags(5) },
        Cell { id: TileID(4), flags: TileFlags(2) },
        Cell { id: TileID(4), flags: TileFlags(2) },
        Cell { id: TileID(3), flags: TileFlags(2) },
        Cell { id: TileID(2), flags: TileFlags(2) },
        Cell { id: TileID(2), flags: TileFlags(2) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(13), flags: TileFlags(5) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(13), flags: TileFlags(5) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(13), flags: TileFlags(5) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(13), flags: TileFlags(5) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(9), flags: TileFlags(2) },
        Cell { id: TileID(10), flags: TileFlags(2) },
        Cell { id: TileID(11), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(14), flags: TileFlags(6) },
        Cell { id: TileID(8), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(8), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(15), flags: TileFlags(7) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(13), flags: TileFlags(101) },
        Cell { id: TileID(8), flags: TileFlags(101) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(8), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(13), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(97) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(13), flags: TileFlags(5) },
        Cell { id: TileID(1), flags: TileFlags(225) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(97) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(13), flags: TileFlags(5) },
        Cell { id: TileID(1), flags: TileFlags(225) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(1) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(97) },
        Cell { id: TileID(18), flags: TileFlags(2) },
        Cell { id: TileID(19), flags: TileFlags(2) },
        Cell { id: TileID(20), flags: TileFlags(2) },
        Cell { id: TileID(21), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(13), flags: TileFlags(5) },
        Cell { id: TileID(21), flags: TileFlags(130) },
        Cell { id: TileID(20), flags: TileFlags(130) },
        Cell { id: TileID(19), flags: TileFlags(130) },
        Cell { id: TileID(18), flags: TileFlags(130) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(225) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(97) },
        Cell { id: TileID(19), flags: TileFlags(2) },
        Cell { id: TileID(20), flags: TileFlags(2) },
        Cell { id: TileID(21), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(13), flags: TileFlags(5) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(21), flags: TileFlags(130) },
        Cell { id: TileID(20), flags: TileFlags(130) },
        Cell { id: TileID(19), flags: TileFlags(130) },
        Cell { id: TileID(18), flags: TileFlags(130) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(225) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(97) },
        Cell { id: TileID(20), flags: TileFlags(2) },
        Cell { id: TileID(21), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(13), flags: TileFlags(5) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(21), flags: TileFlags(130) },
        Cell { id: TileID(20), flags: TileFlags(130) },
        Cell { id: TileID(19), flags: TileFlags(130) },
        Cell { id: TileID(18), flags: TileFlags(130) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(225) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(97) },
        Cell { id: TileID(21), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(22), flags: TileFlags(8) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(12), flags: TileFlags(2) },
        Cell { id: TileID(21), flags: TileFlags(130) },
        Cell { id: TileID(20), flags: TileFlags(130) },
        Cell { id: TileID(19), flags: TileFlags(130) },
        Cell { id: TileID(18), flags: TileFlags(130) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(225) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(97) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(23), flags: TileFlags(9) },
        Cell { id: TileID(23), flags: TileFlags(9) },
        Cell { id: TileID(23), flags: TileFlags(9) },
        Cell { id: TileID(23), flags: TileFlags(9) },
        Cell { id: TileID(23), flags: TileFlags(9) },
        Cell { id: TileID(23), flags: TileFlags(9) },
        Cell { id: TileID(23), flags: TileFlags(9) },
        Cell { id: TileID(23), flags: TileFlags(9) },
        Cell { id: TileID(24), flags: TileFlags(10) },
        Cell { id: TileID(25), flags: TileFlags(10) },
        Cell { id: TileID(26), flags: TileFlags(10) },
        Cell { id: TileID(27), flags: TileFlags(11) },
        Cell { id: TileID(28), flags: TileFlags(11) },
        Cell { id: TileID(28), flags: TileFlags(11) },
        Cell { id: TileID(28), flags: TileFlags(11) },
        Cell { id: TileID(28), flags: TileFlags(11) },
        Cell { id: TileID(28), flags: TileFlags(11) },
        Cell { id: TileID(28), flags: TileFlags(11) },
        Cell { id: TileID(28), flags: TileFlags(11) },
        Cell { id: TileID(28), flags: TileFlags(11) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(225) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(97) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(29), flags: TileFlags(12) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(225) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(225) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(97) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(30), flags: TileFlags(1) },
        Cell { id: TileID(1), flags: TileFlags(225) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(97) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(16), flags: TileFlags(5) },
        Cell { id: TileID(1), flags: TileFlags(225) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(97) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(31), flags: TileFlags(13) },
        Cell { id: TileID(1), flags: TileFlags(225) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(97) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(17), flags: TileFlags(5) },
        Cell { id: TileID(1), flags: TileFlags(225) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(1), flags: TileFlags(193) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
        Cell { id: TileID(0), flags: TileFlags(0) },
    ],
    columns: 36,
    rows: 27,
};

pub const TESTMAP_TILES: [Tile<2>; 32] = [
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [16, 0] },
            Cluster { data: [0, 4] },
            Cluster { data: [64, 0] },
            Cluster { data: [17, 64] },
            Cluster { data: [1, 5] },
            Cluster { data: [64, 21] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [85, 85] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 85] },
            Cluster { data: [0, 0] },
            Cluster { data: [34, 34] },
            Cluster { data: [0, 0] },
            Cluster { data: [34, 34] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [85, 85] },
            Cluster { data: [136, 136] },
            Cluster { data: [85, 85] },
            Cluster { data: [136, 136] },
            Cluster { data: [34, 34] },
            Cluster { data: [136, 136] },
            Cluster { data: [34, 34] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [85, 85] },
            Cluster { data: [170, 170] },
            Cluster { data: [85, 85] },
            Cluster { data: [170, 170] },
            Cluster { data: [34, 34] },
            Cluster { data: [170, 170] },
            Cluster { data: [34, 34] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [5, 80] },
            Cluster { data: [165, 82] },
            Cluster { data: [245, 83] },
            Cluster { data: [165, 82] },
            Cluster { data: [245, 95] },
            Cluster { data: [255, 255] },
            Cluster { data: [255, 255] },
            Cluster { data: [255, 255] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [85, 85] },
            Cluster { data: [170, 170] },
            Cluster { data: [85, 85] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 85] },
            Cluster { data: [5, 85] },
            Cluster { data: [10, 255] },
            Cluster { data: [10, 255] },
            Cluster { data: [2, 191] },
            Cluster { data: [0, 170] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [25, 80] },
            Cluster { data: [25, 80] },
            Cluster { data: [25, 80] },
            Cluster { data: [170, 170] },
            Cluster { data: [149, 84] },
            Cluster { data: [0, 0] },
            Cluster { data: [25, 80] },
            Cluster { data: [25, 80] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [34, 34] },
            Cluster { data: [0, 0] },
            Cluster { data: [34, 34] },
            Cluster { data: [0, 0] },
            Cluster { data: [34, 34] },
            Cluster { data: [0, 0] },
            Cluster { data: [34, 34] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [136, 136] },
            Cluster { data: [34, 34] },
            Cluster { data: [136, 136] },
            Cluster { data: [34, 34] },
            Cluster { data: [136, 136] },
            Cluster { data: [34, 34] },
            Cluster { data: [136, 136] },
            Cluster { data: [34, 34] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [170, 170] },
            Cluster { data: [34, 34] },
            Cluster { data: [170, 170] },
            Cluster { data: [34, 34] },
            Cluster { data: [170, 170] },
            Cluster { data: [34, 34] },
            Cluster { data: [170, 170] },
            Cluster { data: [34, 34] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [25, 80] },
            Cluster { data: [25, 80] },
            Cluster { data: [25, 80] },
            Cluster { data: [25, 80] },
            Cluster { data: [25, 80] },
            Cluster { data: [25, 80] },
            Cluster { data: [25, 80] },
            Cluster { data: [25, 80] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 85] },
            Cluster { data: [5, 170] },
            Cluster { data: [22, 255] },
            Cluster { data: [27, 170] },
            Cluster { data: [110, 170] },
            Cluster { data: [110, 170] },
            Cluster { data: [110, 169] },
            Cluster { data: [110, 165] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [4, 0] },
            Cluster { data: [16, 0] },
            Cluster { data: [85, 85] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [170, 170] },
            Cluster { data: [255, 255] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 144] },
            Cluster { data: [10, 104] },
            Cluster { data: [170, 106] },
            Cluster { data: [169, 169] },
            Cluster { data: [169, 102] },
            Cluster { data: [166, 154] },
            Cluster { data: [166, 170] },
            Cluster { data: [154, 170] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [166, 154] },
            Cluster { data: [170, 166] },
            Cluster { data: [154, 165] },
            Cluster { data: [101, 169] },
            Cluster { data: [89, 89] },
            Cluster { data: [21, 85] },
            Cluster { data: [1, 80] },
            Cluster { data: [80, 20] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 8] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 136] },
            Cluster { data: [0, 0] },
            Cluster { data: [8, 136] },
            Cluster { data: [0, 0] },
            Cluster { data: [136, 136] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 2] },
            Cluster { data: [136, 136] },
            Cluster { data: [0, 34] },
            Cluster { data: [136, 136] },
            Cluster { data: [2, 34] },
            Cluster { data: [136, 136] },
            Cluster { data: [34, 34] },
            Cluster { data: [136, 136] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [34, 34] },
            Cluster { data: [136, 136] },
            Cluster { data: [34, 42] },
            Cluster { data: [136, 136] },
            Cluster { data: [34, 170] },
            Cluster { data: [136, 136] },
            Cluster { data: [42, 170] },
            Cluster { data: [136, 136] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [170, 170] },
            Cluster { data: [136, 138] },
            Cluster { data: [170, 170] },
            Cluster { data: [136, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [138, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [25, 80] },
            Cluster { data: [25, 80] },
            Cluster { data: [25, 80] },
            Cluster { data: [170, 170] },
            Cluster { data: [149, 84] },
            Cluster { data: [0, 0] },
            Cluster { data: [255, 255] },
            Cluster { data: [255, 255] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [80, 1] },
            Cluster { data: [85, 21] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [4, 68] },
            Cluster { data: [160, 2] },
            Cluster { data: [170, 106] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [17, 17] },
            Cluster { data: [68, 68] },
            Cluster { data: [161, 18] },
            Cluster { data: [170, 106] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 85] },
            Cluster { data: [68, 68] },
            Cluster { data: [161, 86] },
            Cluster { data: [170, 106] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [16, 0] },
            Cluster { data: [160, 2] },
            Cluster { data: [170, 42] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [160, 2] },
            Cluster { data: [170, 42] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
            Cluster { data: [170, 170] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [80, 1] },
            Cluster { data: [85, 21] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
            Cluster { data: [85, 85] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 16] },
            Cluster { data: [0, 4] },
            Cluster { data: [16, 5] },
            Cluster { data: [69, 1] },
            Cluster { data: [81, 81] },
            Cluster { data: [149, 85] },
            Cluster { data: [169, 90] },
            Cluster { data: [90, 150] },
        ],
    },
];
