[package]
name = "font"
version = "0.1.0"
edition = "2024"

[dependencies]
tato = { path = "../../" }
tato_raylib = { path = "../../crates/backend_raylib"}
tato_dashboard = { path = "../../crates/dashboard" }

[build-dependencies]
tato_pipe = { path = "../../crates/pipeline" }
