[package]
name = "font"
version = "0.1.0"
edition = "2024"

[dependencies]
tato = { path = "../../" }
backend_raylib = { path = "../_backend/raylib"}

[build-dependencies]
tato_pipe = { path = "../../../tato_pipe" }
