[package]
name = "font"
version = "0.1.0"
edition = "2024"

[dependencies]
tato = { path = "../../" }
tato_raylib = { path = "../../raylib"}

[build-dependencies]
tato_pipe = { path = "../../pipeline" }
