use core::array::from_fn;

use tato_video::*;

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
pub struct TilesetID(pub u8);

/// A collection of tiles and colors. Also keeps track of how a memory bank
/// currently holds that data, so that it can be offloaded.
#[derive(Debug, Clone, Copy)]
pub struct Tileset {
    pub bank_id: u8,
    pub tile_start: u8,
    pub colors: [RGBA12; COLORS_PER_PALETTE as usize],
    pub color_count: u8,
    pub color_mapping_indices: [u8; COLOR_MAPPING_COUNT as usize],
    pub color_mapping_count: u8,
}

/// Generated by tato::Pipeline as a way to convert
/// PNG files into tilesets.
#[derive(Debug, Clone, Copy)]
pub struct TilesetData<'a> {
    pub tiles: Option<&'a [Tile<4>]>,
    pub colors: Option<&'a [RGBA12]>,
    pub color_mappings: Option<&'a [[u8; COLORS_PER_PALETTE as usize]]>,
}

impl Default for Tileset {
    fn default() -> Self {
        Self {
            bank_id: 0,
            tile_start: 0,
            colors: from_fn(|_| RGBA12::default()),
            color_count: 0,
            color_mapping_indices: [0; COLOR_MAPPING_COUNT as usize],
            color_mapping_count: 0,
        }
    }
}
