// Auto-generated code - do not edit manually
use crate::prelude::*;

pub const TILESET_FONT: [Tile<2>; 85] = [
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 84] },
            Cluster { data: [85, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [5, 64] },
            Cluster { data: [21, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [80, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [1, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [21, 0] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [80, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [5, 80] },
            Cluster { data: [0, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [5, 80] },
            Cluster { data: [17, 80] },
            Cluster { data: [65, 80] },
            Cluster { data: [85, 84] },
            Cluster { data: [1, 80] },
            Cluster { data: [1, 80] },
            Cluster { data: [5, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 84] },
            Cluster { data: [80, 0] },
            Cluster { data: [80, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [1, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [1, 80] },
            Cluster { data: [21, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 84] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 84] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 64] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 84] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 64] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 84] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 84] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 84] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [5, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 20] },
            Cluster { data: [84, 80] },
            Cluster { data: [85, 64] },
            Cluster { data: [85, 0] },
            Cluster { data: [85, 64] },
            Cluster { data: [84, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 4] },
            Cluster { data: [85, 20] },
            Cluster { data: [85, 84] },
            Cluster { data: [84, 68] },
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 4] },
            Cluster { data: [85, 4] },
            Cluster { data: [85, 68] },
            Cluster { data: [84, 84] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [85, 68] },
            Cluster { data: [84, 84] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 20] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [85, 64] },
            Cluster { data: [84, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 0] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 84] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [21, 16] },
            Cluster { data: [5, 64] },
            Cluster { data: [1, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 68] },
            Cluster { data: [84, 68] },
            Cluster { data: [84, 68] },
            Cluster { data: [84, 68] },
            Cluster { data: [84, 68] },
            Cluster { data: [84, 68] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [21, 16] },
            Cluster { data: [5, 64] },
            Cluster { data: [21, 16] },
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [84, 4] },
            Cluster { data: [84, 4] },
            Cluster { data: [21, 20] },
            Cluster { data: [5, 80] },
            Cluster { data: [1, 64] },
            Cluster { data: [1, 64] },
            Cluster { data: [1, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [85, 80] },
            Cluster { data: [1, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [21, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [80, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 84] },
            Cluster { data: [85, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 84] },
            Cluster { data: [84, 0] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 84] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [21, 80] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 84] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [85, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 80] },
            Cluster { data: [85, 64] },
            Cluster { data: [84, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [85, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [81, 20] },
            Cluster { data: [81, 20] },
            Cluster { data: [81, 20] },
            Cluster { data: [81, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [84, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 84] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [84, 84] },
            Cluster { data: [85, 64] },
            Cluster { data: [85, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [84, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 84] },
            Cluster { data: [84, 0] },
            Cluster { data: [21, 80] },
            Cluster { data: [0, 84] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [5, 64] },
            Cluster { data: [85, 84] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [84, 20] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [80, 20] },
            Cluster { data: [80, 20] },
            Cluster { data: [20, 80] },
            Cluster { data: [20, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [81, 20] },
            Cluster { data: [81, 20] },
            Cluster { data: [81, 20] },
            Cluster { data: [81, 20] },
            Cluster { data: [85, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [80, 20] },
            Cluster { data: [20, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [21, 80] },
            Cluster { data: [84, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [80, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [5, 80] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 84] },
            Cluster { data: [1, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [21, 0] },
            Cluster { data: [85, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [1, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 84] },
            Cluster { data: [1, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [21, 0] },
            Cluster { data: [5, 64] },
            Cluster { data: [1, 80] },
            Cluster { data: [0, 84] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 80] },
            Cluster { data: [5, 80] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 80] },
            Cluster { data: [5, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 0] },
            Cluster { data: [5, 64] },
            Cluster { data: [1, 80] },
            Cluster { data: [0, 84] },
            Cluster { data: [1, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [21, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 80] },
            Cluster { data: [80, 84] },
            Cluster { data: [0, 84] },
            Cluster { data: [1, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [20, 80] },
            Cluster { data: [20, 80] },
            Cluster { data: [4, 16] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [20, 80] },
            Cluster { data: [85, 84] },
            Cluster { data: [20, 80] },
            Cluster { data: [20, 80] },
            Cluster { data: [85, 84] },
            Cluster { data: [20, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [4, 64] },
            Cluster { data: [21, 84] },
            Cluster { data: [84, 64] },
            Cluster { data: [21, 80] },
            Cluster { data: [4, 84] },
            Cluster { data: [85, 80] },
            Cluster { data: [4, 64] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [20, 20] },
            Cluster { data: [20, 80] },
            Cluster { data: [1, 64] },
            Cluster { data: [5, 0] },
            Cluster { data: [20, 80] },
            Cluster { data: [80, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [21, 0] },
            Cluster { data: [80, 64] },
            Cluster { data: [84, 64] },
            Cluster { data: [21, 68] },
            Cluster { data: [81, 80] },
            Cluster { data: [80, 80] },
            Cluster { data: [21, 20] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [80, 0] },
            Cluster { data: [20, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [1, 64] },
            Cluster { data: [0, 80] },
            Cluster { data: [0, 20] },
            Cluster { data: [0, 5] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [1, 80] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [1, 80] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [5, 64] },
            Cluster { data: [0, 80] },
            Cluster { data: [0, 80] },
            Cluster { data: [0, 80] },
            Cluster { data: [0, 80] },
            Cluster { data: [0, 80] },
            Cluster { data: [5, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [1, 64] },
            Cluster { data: [17, 68] },
            Cluster { data: [5, 80] },
            Cluster { data: [5, 80] },
            Cluster { data: [17, 68] },
            Cluster { data: [1, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [1, 64] },
            Cluster { data: [1, 64] },
            Cluster { data: [21, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [1, 64] },
            Cluster { data: [1, 64] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [1, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [21, 84] },
            Cluster { data: [21, 84] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [5, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 5] },
            Cluster { data: [0, 20] },
            Cluster { data: [0, 80] },
            Cluster { data: [1, 64] },
            Cluster { data: [5, 0] },
            Cluster { data: [20, 0] },
            Cluster { data: [80, 0] },
            Cluster { data: [0, 0] },
        ],
    },
    Tile {
        clusters: [
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [0, 0] },
            Cluster { data: [85, 85] },
            Cluster { data: [0, 0] },
        ],
    },
];
